//
//  JobsRouter.swift
//  JobFinder
//
//  Created Ali Omari on 4/4/19.
//  Copyright © 2019 Ali Omari. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class JobsRouter: JobsWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(jobs:[Job],position: String, lat: Double?, lng: Double?) -> UIViewController {
        let view = R.storyboard.main.jobsViewController()!
        let interactor = JobsInteractor()
        let router = JobsRouter()
        let presenter = JobsPresenter(interface: view, interactor: interactor, router: router)
        
        presenter.jobs = jobs
        presenter.position = position
        presenter.lat = lat
        presenter.lng = lng
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
