//
//  JobsProtocols.swift
//  JobFinder
//
//  Created Ali Omari on 4/4/19.
//  Copyright © 2019 Ali Omari. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol JobsWireframeProtocol: class {
    
}
//MARK: Presenter -
protocol JobsPresenterProtocol: BasePresenterProtocol {
    
    var jobs:[Job]! { get set }
    var position:String! { get set }
    var lat:Double? { get set }
    var lng:Double? { get set }
    
    func didClickOnJob(job:Job)
    func searchDidCompleted(jobs:[Job])
    func searchDidFailed(error:String)
    func didDisplayDataAt(index:Int)
}

//MARK: Interactor -
protocol JobsInteractorProtocol: class {
    
    var presenter: JobsPresenterProtocol?  { get set }
    
    func searchJob(position:String,lat:Double?,lng:Double?,pageNumber:Int)
}

//MARK: View -
protocol JobsViewProtocol: BaseViewProtocol {
    
    var presenter: JobsPresenterProtocol?  { get set }
    func populate()
    func changeActivityIndicatorVisibility(isHidden:Bool)
}
