//
//  JobsInteractor.swift
//  JobFinder
//
//  Created Ali Omari on 4/4/19.
//  Copyright © 2019 Ali Omari. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class JobsInteractor: JobsInteractorProtocol {
    
    weak var presenter: JobsPresenterProtocol?
    
    func searchJob(position: String, lat: Double?, lng: Double?,pageNumber:Int) {
        let provider = DataManager.shared.selectedProvider!
        let params = provider.getParams(lat: lat, lng: lng, position: position,pageNumber: pageNumber)
        let request = GenericRequest(provider: provider, params: params)
        
        SearchService.search(request, success: {[weak self] (jobs) in
            self?.presenter?.searchDidCompleted(jobs: jobs)
        }) {[weak self] (error) in
            self?.presenter?.searchDidFailed(error: error.localizedDescription)
        }
    }
}
