//
//  FindJobProtocols.swift
//  JobFinder
//
//  Created Ali Omari on 4/4/19.
//  Copyright © 2019 Ali Omari. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol FindJobWireframeProtocol: class {
    
    func goToJobsViewController(jobs: [Job], position: String, lat: Double?, lng: Double?)
}
//MARK: Presenter -
protocol FindJobPresenterProtocol: BasePresenterProtocol {
    
    func jobPositionDidChanged(text:String?)
    func jobLocationDidChanged(lat:Double?,lng:Double?)
    func providerDidSelectAtIndex(index:Int)
    func searchButtonDidPressed()
    func searchDidCompleted(jobs:[Job])
    func searchDidFailed(error:String)
}

//MARK: Interactor -
protocol FindJobInteractorProtocol: class {
    
    var presenter: FindJobPresenterProtocol?  { get set }
    
    func searchJob(position:String,lat:Double?,lng:Double?)
}

//MARK: View -
protocol FindJobViewProtocol: BaseViewProtocol {
    
    var presenter: FindJobPresenterProtocol?  { get set }
    func changeSearchButtonState(isEnabled:Bool)
}
