//
//  FindJobRouter.swift
//  JobFinder
//
//  Created Ali Omari on 4/4/19.
//  Copyright © 2019 Ali Omari. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FindJobRouter: FindJobWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        let mainNavigation = R.storyboard.main.mainNavigation()!
        let view = mainNavigation.viewControllers.first as! FindJobViewController
        let interactor = FindJobInteractor()
        let router = FindJobRouter()
        let presenter = FindJobPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return mainNavigation
    }
    
    func goToJobsViewController(jobs: [Job], position: String, lat: Double?, lng: Double?) {
        let vc = JobsRouter.createModule(jobs: jobs, position: position, lat: lat, lng: lng)
        viewController?.navigationController?.pushViewController(vc, animated: true)
    }
}
